### ISSUE TITLE
Where is api capture screen?

### ISSUE THREAD

**Issue by hungcuiga1** [betaCode95/Screeni#1]
Hello @betaCode95 ,thank you for great project. Can you answer me? I can find api to capture screen,Can you show me where it is?

**Comment by betaCode95** [comment]
Hi @hungcuiga1. Sorry for the delayed response. But, the `channelcatch` package is responsible for all the API. All the implementation you can find it in that folder

**Comment by betaCode95** [comment]
Closing this for now. Let me know if that doesn't answer your question
